/**
 * Post a free Tinder profile review as a Reddit comment.
 * Usage: npx tsx --tsconfig scripts/tsconfig.json scripts/reddit-review.ts <reddit-url> [--dry-run]
 */
import fs from 'fs'
import path from 'path'
import readline from 'readline'

// ── Load .env.local (same pattern as test-email.ts) ──────────────────────────
const envPath = path.resolve(process.cwd(), '.env.local')
for (const line of fs.readFileSync(envPath, 'utf-8').split('\n')) {
  const trimmed = line.trim()
  if (!trimmed || trimmed.startsWith('#')) continue
  const eq = trimmed.indexOf('=')
  if (eq === -1) continue
  const key = trimmed.slice(0, eq)
  const val = trimmed.slice(eq + 1).replace(/^["']|["']$/g, '')
  process.env[key] ??= val
}

import {
  analyzeProfile,
  type ProfileAnalysisInput,
} from '../src/lib/ai/pipeline'

// ── Constants ────────────────────────────────────────────────────────────────
const REDDIT_COMMENT_MAX_CHARS = 10_000
const REDDIT_OAUTH_URL = 'https://www.reddit.com/api/v1/access_token'
const REDDIT_API_BASE = 'https://oauth.reddit.com'
const USER_AGENT = 'TinderProfileOptimizer/1.0 (by /u/TinderProfileOptimize)'

const CTA_FOOTER = `\n\n---\n\n*This free review was generated by [Tinder Profile Optimizer](https://www.tinderprofileoptimizer.com). Full reviews with photo ranking, bio rewrites, and tailored prompts are $29 and delivered to your inbox in minutes.*`

// ── CLI args ─────────────────────────────────────────────────────────────────
const args = process.argv.slice(2)
const dryRun = args.includes('--dry-run')
const url = args.find((a) => !a.startsWith('--'))

if (!url) {
  console.error(
    'Usage: npx tsx --tsconfig scripts/tsconfig.json scripts/reddit-review.ts <reddit-url> [--dry-run]',
  )
  process.exit(1)
}

// ── Helpers ──────────────────────────────────────────────────────────────────
function decodeHtmlEntities(s: string): string {
  return s.replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
}

function parseDemographics(title: string): {
  age: number | null
  gender: string | null
} {
  // Patterns: "27M", "M27", "27, Male", "[25F]", "27, M, Straight", "27/M"
  const patterns = [
    /\b(\d{1,2})\s*[,/]?\s*(?:\[)?([MFmf](?:ale|emale)?)\b/,
    /\b([MFmf](?:ale|emale)?)\s*[,/]?\s*(\d{1,2})\b/,
    /\[(\d{1,2})([MFmf])\]/,
  ]

  for (const pattern of patterns) {
    const match = title.match(pattern)
    if (!match) continue

    // Figure out which group is age vs gender
    const g1 = match[1]
    const g2 = match[2]
    const isG1Numeric = /^\d+$/.test(g1)
    const ageStr = isG1Numeric ? g1 : g2
    const genderStr = isG1Numeric ? g2 : g1

    const age = parseInt(ageStr, 10)
    if (age < 18 || age > 99) continue

    const genderChar = genderStr.charAt(0).toUpperCase()
    const gender = genderChar === 'M' ? 'Male' : 'Female'

    return { age, gender }
  }

  return { age: null, gender: null }
}

interface RedditPostData {
  name: string // fullname e.g. t3_abc123
  title: string
  selftext: string
  imageUrls: string[]
}

async function fetchRedditPost(postUrl: string): Promise<RedditPostData> {
  // Normalize URL: strip trailing slash, append .json
  const normalized = postUrl.replace(/\/+$/, '')
  const jsonUrl = normalized.endsWith('.json')
    ? normalized
    : `${normalized}.json`

  const response = await fetch(jsonUrl, {
    headers: { 'User-Agent': USER_AGENT },
  })
  if (!response.ok) {
    throw new Error(
      `Reddit fetch failed: ${response.status} ${response.statusText}`,
    )
  }

  const data = await response.json()
  const post = data[0]?.data?.children?.[0]?.data
  if (!post) throw new Error('Could not parse Reddit post data')

  const { name, title, selftext } = post
  const imageUrls: string[] = []

  // Gallery posts: media_metadata + gallery_data
  if (post.gallery_data?.items && post.media_metadata) {
    for (const item of post.gallery_data.items) {
      const media = post.media_metadata[item.media_id]
      if (!media) continue

      // Prefer highest-res source image
      if (media.s?.u) {
        imageUrls.push(decodeHtmlEntities(media.s.u))
      } else if (media.s?.gif) {
        imageUrls.push(decodeHtmlEntities(media.s.gif))
      }
    }
  }

  // Single-image fallback
  if (imageUrls.length === 0) {
    if (post.url && /\.(jpg|jpeg|png|gif|webp)(\?|$)/i.test(post.url)) {
      imageUrls.push(decodeHtmlEntities(post.url))
    } else if (post.preview?.images) {
      for (const img of post.preview.images) {
        if (img.source?.url) {
          imageUrls.push(decodeHtmlEntities(img.source.url))
        }
      }
    }
  }

  if (imageUrls.length === 0) {
    throw new Error('No images found in Reddit post')
  }

  return { name, title, selftext, imageUrls }
}

function formatForReddit(report: string): string {
  const text = report + CTA_FOOTER

  if (text.length <= REDDIT_COMMENT_MAX_CHARS) return text

  // Progressive truncation: drop Conversation Prompts section first
  const promptsRegex = /## Conversation Prompts[\s\S]*?(?=## |$)/
  const trimmed = report.replace(promptsRegex, '').trim() + CTA_FOOTER
  if (trimmed.length <= REDDIT_COMMENT_MAX_CHARS) return trimmed

  // Hard truncate as last resort
  const suffix =
    '\n\n*(Review truncated due to Reddit character limits)*' + CTA_FOOTER
  return report.slice(0, REDDIT_COMMENT_MAX_CHARS - suffix.length) + suffix
}

function confirm(question: string): Promise<boolean> {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  })
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      rl.close()
      resolve(answer.toLowerCase().startsWith('y'))
    })
  })
}

async function getRedditAccessToken(): Promise<string> {
  const {
    REDDIT_CLIENT_ID,
    REDDIT_CLIENT_SECRET,
    REDDIT_USERNAME,
    REDDIT_PASSWORD,
  } = process.env
  if (
    !REDDIT_CLIENT_ID ||
    !REDDIT_CLIENT_SECRET ||
    !REDDIT_USERNAME ||
    !REDDIT_PASSWORD
  ) {
    throw new Error(
      'Missing Reddit credentials. Set REDDIT_CLIENT_ID, REDDIT_CLIENT_SECRET, REDDIT_USERNAME, REDDIT_PASSWORD in .env.local',
    )
  }

  const credentials = Buffer.from(
    `${REDDIT_CLIENT_ID}:${REDDIT_CLIENT_SECRET}`,
  ).toString('base64')

  const response = await fetch(REDDIT_OAUTH_URL, {
    method: 'POST',
    headers: {
      Authorization: `Basic ${credentials}`,
      'Content-Type': 'application/x-www-form-urlencoded',
      'User-Agent': USER_AGENT,
    },
    body: new URLSearchParams({
      grant_type: 'password',
      username: REDDIT_USERNAME,
      password: REDDIT_PASSWORD,
    }),
  })

  if (!response.ok) {
    throw new Error(
      `Reddit auth failed: ${response.status} ${response.statusText}`,
    )
  }

  const tokenData = await response.json()
  if (!tokenData.access_token) {
    throw new Error(`Reddit auth error: ${JSON.stringify(tokenData)}`)
  }

  return tokenData.access_token
}

async function postRedditComment(
  accessToken: string,
  thingId: string,
  text: string,
): Promise<void> {
  const response = await fetch(`${REDDIT_API_BASE}/api/comment`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${accessToken}`,
      'Content-Type': 'application/x-www-form-urlencoded',
      'User-Agent': USER_AGENT,
    },
    body: new URLSearchParams({
      thing_id: thingId,
      text,
      api_type: 'json',
    }),
  })

  if (response.status === 429) {
    const retryAfter = response.headers.get('retry-after')
    throw new Error(
      `Rate limited by Reddit. Retry after ${retryAfter ?? 'unknown'} seconds.`,
    )
  }

  if (!response.ok) {
    const body = await response.text()
    throw new Error(`Reddit comment failed (${response.status}): ${body}`)
  }

  const result = await response.json()
  const errors = result?.json?.errors
  if (errors?.length) {
    throw new Error(`Reddit API errors: ${JSON.stringify(errors)}`)
  }

  console.log('Comment posted successfully!')
}

// ── Main ─────────────────────────────────────────────────────────────────────
async function main() {
  console.log('Fetching Reddit post...')
  const post = await fetchRedditPost(url!)

  console.log(`Title: ${post.title}`)
  console.log(`Images found: ${post.imageUrls.length}`)

  const { age, gender } = parseDemographics(post.title)
  if (age || gender) {
    console.log(`Demographics: age=${age}, gender=${gender}`)
  }

  console.log('\nRunning AI analysis...')
  const input: ProfileAnalysisInput = {
    imageUrls: post.imageUrls,
    datingGoal: 'Get more matches and improve my profile',
    aboutUser: post.selftext || '',
    age,
    location: null,
    gender,
    lookingFor: null,
  }

  const { report } = await analyzeProfile(input)

  const formatted = formatForReddit(report)
  console.log('\n' + '='.repeat(60))
  console.log(formatted)
  console.log('='.repeat(60))
  console.log(
    `\nCharacter count: ${formatted.length} / ${REDDIT_COMMENT_MAX_CHARS}`,
  )

  if (dryRun) {
    console.log('\n--dry-run: skipping comment post.')
    return
  }

  const shouldPost = await confirm('\nPost this comment to Reddit? (y/n) ')
  if (!shouldPost) {
    console.log('Aborted.')
    return
  }

  console.log('Authenticating with Reddit...')
  const accessToken = await getRedditAccessToken()

  console.log('Posting comment...')
  await postRedditComment(accessToken, post.name, formatted)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
